### ISSUE TITLE
Testing with enzyme

### ISSUE THREAD

**Issue by JakeGinnivan** [nfl/react-gpt#11]
Hey all,

It appears there are some issues when testing and the gpt compoent gets unmounted. This exception is thrown a fair bit:

```
     Uncaught TypeError: Cannot read property 'getSizes' of undefined
      at getSize (node_modules\react-gpt\lib\utils\mockGPT.js:42:21)
      at node_modules\react-gpt\lib\utils\mockGPT.js:311:52
      at Array.forEach (native)
      at node_modules\react-gpt\lib\utils\mockGPT.js:303:43
      at Array.forEach (native)
      at Timeout._onTimeout (node_modules\react-gpt\lib\utils\mockGPT.js:301:43)
```

Any ideas on the best way to resolve this?

**Comment by taak77** [comment]
@JakeGinnivan thanks for reporting, do you have a minimum code I can reproduce?

**Comment by potench** [comment]
Closing this due to inactivity. @JakeGinnivan feel free to add your test code to the issue so we can try to reproduce, if you do then I'll reopen
